module Hound
  CHANGED_FILES_THRESHOLD ||= ENV.fetch('CHANGED_FILES_THRESHOLD').to_i
  HTTPS_ENABLED ||= ENV.fetch('ENABLE_HTTPS') == 'yes'
  GITLAB_API_URL ||= ENV.fetch('GITLAB_API_URL')
  GITLAB_APPLICATION_KEY ||= ENV.fetch('GITLAB_APPLICATION_KEY')
  GITLAB_APPLICATION_SECRET ||= ENV.fetch('GITLAB_APPLICATION_SECRET')
  HOST ||= ENV.fetch('HOST')
  GITLAB_TOKEN ||= ENV.fetch('HOUND_GITLAB_TOKEN')
  GITLAB_USERNAME ||= ENV.fetch('HOUND_GITLAB_USERNAME')
  INTERCOM_API_SECRET ||= ENV.fetch('INTERCOM_API_SECRET')
  MAX_COMMENTS ||= ENV.fetch('MAX_COMMENTS').to_i
  SEGMENT_KEY ||= ENV.fetch('SEGMENT_KEY')
  STRIPE_PUBLISHABLE_KEY ||= ENV.fetch('STRIPE_PUBLISHABLE_KEY')
end
